CREATE TABLE LOG
(
	LOG_ID NVARCHAR(50) PRIMARY KEY NOT NULL,
	USER_ID VARCHAR(10) NOT NULL,
    ACTION_TIME DATETIME,
    ACTION_DATE DATE,
    LOG_DESCRIPTION NVARCHAR(200),
    FOREIGN KEY (USER_ID) REFERENCES INFO_USUARIO(COD_TITULO)
);

CREATE TABLE AUTORIZACAO
(
	AUT_ID VARCHAR(50) PRIMARY KEY, -- ID DA AUTORIZAÇÃO
	USER_ID VARCHAR(10) NOT NULL, -- ID DO USUARIO
    AUT_BY VARCHAR(10) NOT NULL, -- AUTORIZADO POR
    ACTION_DATE DATE, -- DATA DA AUTORIZAÇÃO
    CAN_VOTE ENUM('Y', 'N') DEFAULT 'N',   -- PODE VOTAR? 
	ALREADY_VOTED ENUM('Y', 'N') DEFAULT 'N',   -- JA VOTOU? 
    FOREIGN KEY (USER_ID) REFERENCES INFO_USUARIO(COD_TITULO),
    FOREIGN KEY (AUT_BY) REFERENCES INFO_USUARIO(COD_TITULO)
);

CREATE TABLE VOTOS
(
	VOTO_ID INT(5) PRIMARY KEY AUTO_INCREMENT,
	USER_ID VARCHAR(10) UNIQUE NOT NULL, -- ID DO USUARIO
    CAND_ID int(4) NOT NULL, -- CÓDIGO DO CANDIDATO
    FOREIGN KEY (USER_ID) REFERENCES INFO_USUARIO(COD_TITULO),
    FOREIGN KEY (CAND_ID) REFERENCES CANDIDATOS(NUMERO)
);

INSERT INTO UNIDADE_FEDERACAO VALUES
('SP', 'SÃO PAULO'),
('SC', 'SANTA CATARINA'),
('CE', 'CEARÁ'),
('BA', 'BAHIA');

INSERT INTO ZONA_ELEITORAL VALUES
(1, 123, 'SP'),
(2, 132, 'SC');

INSERT INTO NIVEL VALUES
(1, 'USUÁRIO COMUM'),
(2, 'MESÁRIO'),
(3, 'CHEFE DE SEÇÃO');

INSERT INTO MUNICIPIOS VALUES
(123, 'SÃO JOSÉ DOS CAMPOS', 'SP');

INSERT INTO INFO_USUARIO (COD_TITULO, DATA_EMISSAO, ZONA, SECAO_ELEITORAL, NOME, DATA_NASC, NIVEL, SENHA) VALUES
('123456', '2018-01-15', 1, 123, 'Mauricio de Souza', '2000-03-03', 1, '123456'),
('654321', '2017-03-10', 1, 123, 'JOAO PAULO', '1989-12-12', 2, '654321'),
('987654', '2016-02-05', 1, 123, 'Vladmir Temer', '1945-10-10', 3, '987654');

select * from info_usuario;

INSERT INTO CANDIDATOS VALUES
(13, 'LULA', 0),
(17, 'BOLSONAURO', 0),
(50, 'BOULOS', 0),
(51, 'DACIOLO', 0),
(0, 'BRANCO', 0),
(1, 'NULO', 0);

-- AREA PARA TESTAR O TRIGGER
SET SQL_SAFE_UPDATES = 0;

-- TRIGGER PARA ATUALIZAR ESTOQUE QUANDO OCORRER UMA pedido
DELIMITER $
CREATE TRIGGER atualizaVotos 
AFTER INSERT ON VOTOS 
FOR EACH ROW 
BEGIN
UPDATE CANDIDATOS 
SET VOTOS = VOTOS + 1
WHERE NUMERO = NEW.CAND_ID;
END$
#delimiter
-- FIM DO TRIGGER

#INSERT INTO VOTOS VALUES
#(1, '123456', 51);

